"""add user points

Revision ID: 842120057e5b
Revises: e7d23d8fc54c
Create Date: 2026-02-17 14:17:42.588418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842120057e5b'
down_revision = 'e7d23d8fc54c'
branch_labels = None
depends_on = None


def upgrade():
    
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))

    
    op.execute("UPDATE user SET points = 0")


    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('points', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('points')

    # ### end Alembic commands ###
